# SECOND STEP OF ETL : TRANSFORM

In [59]:
import pandas as pd

In [60]:
data = pd.read_csv("data.csv")
data.head()

,Poste,Entreprise,Ville,Type de contrat,Expérience,Lien
0,Financial Reporting Manager,Cypher,Casablanca,CDI,6-9,https://www.jobzyn.com/fr/companies/cypher/job...
1,Responsable HSE,TGCC,Casablanca,CDD,6-9,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
2,Responsable études de prix,TGCC,Casablanca,CDI,6-9,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
3,Talent Acquisition Specialist,Theodo Morocco,Casablanca,CDI,0-2,https://www.jobzyn.com/fr/companies/theodo-mor...
4,Consulting Data Manager,ARTEFACT,Casablanca,CDI,3-5,https://www.jobzyn.com/fr/companies/artefact/j...

In [61]:
data.shape

(271, 6)

In [62]:
data.isna( ).sum(axis=0)

Poste               0
Entreprise          0
Ville              10
Type de contrat     0
Expérience          0
Lien                0
dtype: int64

In [63]:
data.duplicated().sum()

np.int64(0)

In [64]:
data.describe()

,Poste,Entreprise,Ville,Type de contrat,Expérience,Lien
count,271,271,261,271,271,271
unique,257,37,11,5,4,271
top,Conseiller(e) Commercial en mobilier,Glovo,Casablanca,CDI,3-5,https://www.jobzyn.com/fr/companies/agenz/jobs...
freq,3,32,217,253,148,1

In [65]:
data["Expérience"] = data["Expérience"].str.replace(r"[^0-9\-]", "", regex=True)  # Keep only numbers & "-"
data["Expérience"] = data["Expérience"].apply(lambda x: x + " ans" if x != "-" else x)

In [66]:
data.head(15)

,Poste,Entreprise,Ville,Type de contrat,Expérience,Lien
0,Financial Reporting Manager,Cypher,Casablanca,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/cypher/job...
1,Responsable HSE,TGCC,Casablanca,CDD,6-9 ans,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
2,Responsable études de prix,TGCC,Casablanca,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
3,Talent Acquisition Specialist,Theodo Morocco,Casablanca,CDI,0-2 ans,https://www.jobzyn.com/fr/companies/theodo-mor...
4,Consulting Data Manager,ARTEFACT,Casablanca,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/artefact/j...
5,Data consultant,Akumenia,Casablanca,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/Akumenia/j...
6,Chief Technical Officer,Akumenia,Casablanca,CDI,10- ans,https://www.jobzyn.com/fr/companies/Akumenia/j...
7,KAM Clinique Rabat/Fes/Meknes Oriental,Sterifil,Rabat,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/sterifil/j...
8,Développeur Web Senior,Theodo Morocco,Casablanca,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/theodo-mor...
9,Responsable Technique,Maghreb Industries,Nouasseur,CDI,10- ans,https://www.jobzyn.com/fr/companies/Maghreb-In...
10,Responsable Méthodes,Maghreb Industries,Nouasseur,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/Maghreb-In...
11,Responsable de Production,Maghreb Industries,Nouasseur,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/Maghreb-In...
12,Responsable Trésorerie,Maghreb Industries,Nouasseur,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/Maghreb-In...
13,Senior Web Developer React/Spring Boot,Theodo Morocco,Casablanca,Freelance,3-5 ans,https://www.jobzyn.com/fr/companies/theodo-mor...
14,UI/UX Designer,Theodo Morocco,Casablanca,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/theodo-mor...

In [67]:
data['Ville'].fillna("Non spécifiée", inplace=True)

C:\Users\Aymane\AppData\Local\Temp\ipykernel_13660\1536008485.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Ville'].fillna("Non spécifiée", inplace=True)

In [68]:
data.head(114)

,Poste,Entreprise,Ville,Type de contrat,Expérience,Lien
0,Financial Reporting Manager,Cypher,Casablanca,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/cypher/job...
1,Responsable HSE,TGCC,Casablanca,CDD,6-9 ans,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
2,Responsable études de prix,TGCC,Casablanca,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
3,Talent Acquisition Specialist,Theodo Morocco,Casablanca,CDI,0-2 ans,https://www.jobzyn.com/fr/companies/theodo-mor...
4,Consulting Data Manager,ARTEFACT,Casablanca,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/artefact/j...
...,...,...,...,...,...,...
109,Consultant associate,Accuracy,Casablanca,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/accuracy/j...
110,Back-end Developer (Symfony),Sobrus,Non spécifiée,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/sobrus/job...
111,Sales Executive - Casablanca,Glovo,Casablanca,CDI,0-2 ans,https://www.jobzyn.com/fr/companies/glovo/jobs...
112,Sales Executive - Rabat,Glovo,Rabat,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/glovo/jobs...
113,Électricien Industriel,Maghreb Industries,Nouasseur,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/Maghreb-In...

In [69]:
def clean_poste(poste):
    if " - " in poste:  
        return poste.rsplit(" - ", 1)[0] 
    return poste  

data["Poste"] = data["Poste"].apply(clean_poste)

In [70]:
data.head(177)

,Poste,Entreprise,Ville,Type de contrat,Expérience,Lien
0,Financial Reporting Manager,Cypher,Casablanca,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/cypher/job...
1,Responsable HSE,TGCC,Casablanca,CDD,6-9 ans,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
2,Responsable études de prix,TGCC,Casablanca,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/TGCC/jobs/...
3,Talent Acquisition Specialist,Theodo Morocco,Casablanca,CDI,0-2 ans,https://www.jobzyn.com/fr/companies/theodo-mor...
4,Consulting Data Manager,ARTEFACT,Casablanca,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/artefact/j...
...,...,...,...,...,...,...
172,Chef de projets H/F (Aménagement Urbain & Façade),Mafoder,Non spécifiée,CDI,6-9 ans,https://www.jobzyn.com/fr/companies/mafoder/jo...
173,Senior Product Manager SaaS (Univers pharmacie),Sobrus,Témara,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/sobrus/job...
174,Responsable Grands Comptes,YoLa Fresh,Casablanca,CDI,10- ans,https://www.jobzyn.com/fr/companies/yola-fresh...
175,Responsable des Opérations,KITEA,Rabat,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/kitea/jobs...
176,Product & Delivery Consultant,Theodo Morocco,Casablanca,CDI,3-5 ans,https://www.jobzyn.com/fr/companies/theodo-mor...

In [71]:
data.to_csv("cleaned_data.csv", index=False, encoding="utf-8")